version: "3.9"
services:
  # Loki
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  # Tempo
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "4317:4317"   # OTLP gRPC / Tempo ingest (also used by Alloy)
      - "3200:3200"   # Tempo query (Grafana)

  # Prometheus (用于抓取 Alloy 暴露的 metrics)
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    ports:
      - "9090:9090"

  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"

  # Alloy (做 collector/agent)
  alloy:
    image: grafana/alloy:v1.10.1
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
    ports:
      - "12345:12345"   # Alloy UI/API
      - "9464:9464"     # Prometheus metrics 暴露端口
      - "4318:4318"     # OTLP HTTP
      - "4319:4319"     # OTLP gRPC（新增）
      - "9999:9999"
    depends_on:
      - loki
      - tempo
      - pyroscope
      - prometheus

  # Grafana
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
      - pyroscope
      - prometheus

networks:
  default:
    name: observability-net
